apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-pod
  labels:
    project: kubernetes-project
spec:
  containers:
    - name: kubernetes-pod
      image: educative1/kubernetes-project:v2
      ports:
        - containerPort: 31111